{
 "title": "Data Ingestion Monitoring Dashboard",
 "description": "Quickly highlight if data ingestion is healthy or if there are quality issues.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Validation Error Types by Frequency",
   "type": "barchart",
   "description": "A breakdown of different error types and how many times each occurred, over the time range selected in Grafana dashboard.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  error_type,\r\n  SUM((error_details->>error_type)::int) AS count\r\nFROM data_quality_stats,\r\nLATERAL jsonb_object_keys(error_details) AS error_type\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY error_type\r\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Recent ingested files with row validation stats and severity level",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  filename,\r\n  valid_rows,\r\n  invalid_rows,\r\n  severity,\r\n  timestamp AS created_on\r\nFROM data_quality_stats\r\nORDER BY timestamp DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "% Invalid Rows (Last 10m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "\n                SELECT\n                    timestamp AS time,\n                    (invalid_rows::float / NULLIF(total_rows, 0)) * 100 AS value\n                FROM data_quality_stats\n                WHERE $__timeFilter(timestamp)\n                ORDER BY timestamp\n                "
    }
   ]
  },
  {
   "title": "percentage distribution of severity levels",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \n  COALESCE(severity, 'Unknown') AS severity_label,\n  ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS percentage\nFROM data_quality_stats\nGROUP BY severity;"
    }
   ]
  }
 ]
}