{
 "title": "Data drift and prediction issues dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Airline Distribution - Data Drift ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH all_airlines AS (\n  SELECT DISTINCT airline FROM flight_data\n  UNION\n  SELECT DISTINCT airline FROM predictions\n),\ntraining_counts AS (\n  SELECT airline, COUNT(*) AS count\n  FROM flight_data\n  GROUP BY airline\n),\nserving_counts AS (\n  SELECT airline, COUNT(*) AS count\n  FROM predictions\n  GROUP BY airline\n),\ntotal_counts AS (\n  SELECT (SELECT COUNT(*) FROM flight_data) AS training_total,\n         (SELECT COUNT(*) FROM predictions) AS serving_total\n),\ncombined AS (\n  SELECT a.airline,\n         COALESCE(t.count, 0) AS training_count,\n         COALESCE(s.count, 0) AS serving_count,\n         total_counts.training_total,\n         total_counts.serving_total\n  FROM all_airlines a\n  LEFT JOIN training_counts t ON a.airline = t.airline\n  LEFT JOIN serving_counts s ON a.airline = s.airline\n  CROSS JOIN total_counts\n)\nSELECT airline,\n       (training_count * 100.0 / training_total) AS training_percentage,\n       (serving_count * 100.0 / serving_total) AS serving_percentage\nFROM combined\nORDER BY airline;"
    }
   ]
  },
  {
   "title": "Flight Duration Trend - Data Drift",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH all_bins AS (\n  SELECT generate_series(0, 18, 2) AS duration_bin\n),\ntraining_counts AS (\n  SELECT FLOOR(CAST(duration AS DOUBLE PRECISION) / 2) * 2 AS duration_bin, \n         COUNT(*) AS frequency,\n         SUM(COUNT(*)) OVER () AS total_training_count\n  FROM flight_data\n  GROUP BY duration_bin\n),\nserving_counts AS (\n  SELECT FLOOR(CAST(duration AS DOUBLE PRECISION) / 2) * 2 AS duration_bin, \n         COUNT(*) AS frequency,\n         SUM(COUNT(*)) OVER () AS total_serving_count\n  FROM predictions\n  GROUP BY duration_bin\n)\nSELECT \n  b.duration_bin,\n  COALESCE(ROUND((t.frequency::FLOAT / t.total_training_count * 100)::NUMERIC, 2), 0) AS training_frequency_percent,\n  COALESCE(ROUND((s.frequency::FLOAT / s.total_serving_count * 100)::NUMERIC, 2), 0) AS serving_frequency_percent\nFROM all_bins b\nLEFT JOIN training_counts t ON b.duration_bin = t.duration_bin\nLEFT JOIN serving_counts s ON b.duration_bin = s.duration_bin\nORDER BY b.duration_bin;"
    }
   ]
  },
  {
   "title": "Predicted Price Trend (Within Range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    prediction_time,\n    predicted_price\nFROM predictions\nWHERE $__timeFilter(prediction_time)\nORDER BY prediction_time;"
    }
   ]
  },
  {
   "title": "Absolute Error in Flight Price Predictions (Top 5 Routes Effected)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH LatestPredictions AS (\n    SELECT DISTINCT ON (p.airline, p.source_city, p.destination_city, p.travel_class, p.stops, p.departure_time, p.arrival_time, p.days_left)\n        p.airline,\n        p.source_city,\n        p.destination_city,\n        p.travel_class,\n        p.stops,\n        p.departure_time,\n        p.arrival_time,\n        p.days_left,\n        p.predicted_price,\n        t.price AS training_price,\n        ROUND(ABS(p.predicted_price::numeric - t.price::numeric), 2) AS absolute_error\n    FROM predictions p\n    JOIN flight_data t \n        ON p.airline = t.airline\n        AND p.source_city = t.source_city\n        AND p.destination_city = t.destination_city\n        AND p.travel_class = t.travel_class\n        AND p.stops = t.stops\n        AND p.departure_time = t.departure_time\n        AND p.arrival_time = t.arrival_time\n        AND p.days_left = t.days_left::INTEGER\n        AND p.duration = t.duration::FLOAT\n    WHERE p.prediction_time >= NOW() - INTERVAL '60 minutes'\n    ORDER BY p.airline, p.source_city, p.destination_city, p.travel_class, p.stops, p.departure_time, p.arrival_time, p.days_left, p.prediction_time DESC\n)\nSELECT \n    airline,\n    source_city || ' to ' || destination_city AS route,\n    travel_class,\n    stops,\n    departure_time,\n    arrival_time,\n    training_price::INTEGER,\n    predicted_price,\n    absolute_error\nFROM LatestPredictions\nORDER BY absolute_error DESC\nLimit 5;"
    }
   ]
  },
  {
   "title": "Prediction Type Frequency (Last 60 Minutes)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT prediction_type, COUNT(*) \nFROM predictions\nWHERE $__timeFilter(prediction_time)\nGROUP BY prediction_type;"
    }
   ]
  }
 ]
}