{
 "title": "Data Drift & Prediction Issues Dashboard",
 "description": "Purpose: Track prediction output consistency and detect unusual patterns or data drifts.",
 "time": { "from": "2025-07-04T21:26:29.901Z", "to": "2025-07-05T09:26:29.901Z" },
 "panels": [
  {
   "title": " Prediction Source Distribution",
   "type": "barchart",
   "description": "Which app/scheduler is dominating usage?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT prediction_source, COUNT(*) \r\nFROM predictions\r\nWHERE prediction_time >= now() - interval '60 minutes'\r\nGROUP BY prediction_source;\r\n"
    }
   ]
  },
  {
   "title": "Predictions for last 60 minutes for custom route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  airline,\n  source_city,\n  destination_city,\n  travel_class,\n  predicted_price,\n  prediction_time\nFROM predictions\nWHERE prediction_time >= NOW() - INTERVAL '60 minutes'\n  AND days_left>20\n  AND source_city = 'Delhi'\n  AND destination_city = 'Mumbai'\nORDER BY prediction_time DESC;"
    }
   ]
  },
  {
   "title": "Flight Price Prediction Model Error by Airline and Route-- Based on predictions by using interval",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (p.airline, p.source_city, p.destination_city)\n    p.airline,\n    p.source_city,\n    p.destination_city,\n    p.predicted_price,\n    t.price AS training_price,\n    ROUND(ABS(p.predicted_price::numeric - t.price::numeric), 2) AS absolute_error\nFROM predictions p\nJOIN flight_data t \n  ON p.airline = t.airline\n AND p.source_city = t.source_city\n AND p.destination_city = t.destination_city\nWHERE p.prediction_time >= NOW() - INTERVAL '60 minutes'\nORDER BY p.airline, p.source_city, p.destination_city, p.prediction_time DESC;"
    }
   ]
  },
  {
   "title": "Predicted Price Buckets (Last 7 Days)",
   "type": "histogram",
   "description": "This query is grouping flight price predictions into rounded price buckets and counting how many predictions fall into each bucket over the last 7 days\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \n  ROUND(predicted_price, -2) AS price_bucket,\n  COUNT(*) AS count\nFROM predictions\nWHERE prediction_time >= NOW() - INTERVAL '7 days'\nGROUP BY price_bucket\nORDER BY price_bucket;\n"
    }
   ]
  },
  {
   "title": "Detecting price drift Across airlines",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \n    t.airline,\n    t.source_city,\n    t.destination_city,\n    MIN(t.price) AS flight_data,\n    MIN(p.predicted_price) AS predicted_price\nFROM flight_data t\nJOIN predictions p \n  ON t.airline = p.airline \n AND t.source_city = p.source_city \n AND t.destination_city = p.destination_city\nWHERE t.source_city = 'Delhi'\n  AND t.destination_city = 'Mumbai'\nGROUP BY t.airline, t.source_city, t.destination_city\nORDER BY t.airline\nLIMIT 2000;"
    }
   ]
  }
 ]
}